spring:

  cloud:
    gateway:
      enabled: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:106.14.44.108}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:123}
    password: ${RABBIT_MQ_PASSWORD:123}

  redis:
    host: ${REDIS_HOST :106.14.44.108}
    port: ${REDIS_PORT:6379}
    # password: ${REDIS_PASSWORD:}
    # Lettuce的连接是基于Netty
    lettuce:
      pool:
        max-active: 300

management:
  endpoints:
    web:
      exposure:
        include: '*'

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: fun.neverth
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:106.14.44.108}
      port: ${REDIS_PORT:6379}