spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.44.108:3306/icibei_gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: ly19980911

# 网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs,/words,/user

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework: debug
