spring:

#  rabbitmq:
#    host: ${RABBIT_MQ_HOST:106.14.44.108}
#    port: ${RABBIT_MQ_PORT:5672}
#    username: ${RABBIT_MQ_USERNAME:123}
#    password: ${RABBIT_MQ_PASSWORD:123}
#
#  redis:
#    host: ${REDIS_HOST :106.14.44.108}
#    port: ${REDIS_PORT:6379}
#    # password: ${REDIS_PASSWORD:}
#    # Lettuce的连接是基于Netty
#    lettuce:
#      pool:
#        max-active: 300

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.44.108:3306/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: ly19980911

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)

logging:
  level:
    org.springframework: debug
    fun.neverth: debug
    java.sql.PreparedStatement: debug
